import pandas as pd

# Lista de 30 palavras
palavras = [
    "algoritmo",
    "programação",
    "desenvolvedor",
    "código",
    "software",
    "hardware",
    "internet",
    "segurança",
    "criptografia",
    "nuvem",
    "servidor",
    "protocolo",
    "firewall",
    "cache",
    "interface",
    "usuário",
    "acessibilidade",
    "inovação",
    "automação",
    "robótica",
    "inteligência",
    "artificial",
    "aprendizado",
    "máquina",
    "realidade",
    "virtual",
    "deep learning",
    "blockchain",
    "dispositivo",
    "móvel",
    "aplicativo",
    "atualização",
    "sistema",
    "operacional",
    "integração",
    "api",
    "backend",
    "frontend",
    "website",
    "e-commerce",
    "programador",
    "engenharia",
    "de software",
    "linguagem",
    "compilação",
    "depuração",
    "bug",
    "computação",
    "quântica",
    "nanotecnologia",
    "realidade",
    "aumentada",
    "big data",
    "análise",
    "dados",
    "cibersegurança",
    "vulnerabilidade",
    "ataque",
    "phishing",
    "malware",
    "criptomoeda",
    "bitcoin",
    "ethereum",
    "5g",
    "iot",
    "automação",
    "veicular",
    "impressão",
    "3d",
    "drone",
    "realidade",
    "mista",
    "biometria",
    "reconhecimento",
    "facial",
    "assistente",
    "virtual",
    "machine",
    "vision",
    "de recomendação",
    "computação",
    "em nuvem",
    "geolocalização",
    "realidade",
    "aumentada",
    "desenvolvimento",
    "ágil",
    "sprint",
    "escopo",
    "teste",
    "qualidade",
    "usabilidade",
    "experiência",
    "do usuário"
]

df = pd.DataFrame({'Palavra': palavras})

# Salvar o DataFrame em um arquivo CSV sem a coluna de índice
df.to_csv('palavras.csv', index=False)
